version: "3.4"
services:
  commercebackend:
    container_name: commercebackend
    restart: unless-stopped
    image: danielyaghoobian/commercebackend:latest
    networks:
      z_internal:
    environment:
      - CLIENT_ORIGIN_URL=${CLIENT_ORIGIN_URL}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - MONGOURI=${MONGOURI}
      - DATABASENAME=${DATABASENAME}
networks:
  z_internal:
    external: true